name: Node
run-name: ${{ github.actor }} is testing node version
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: pnpm

      - run: pnpm install

      - name: Validate code with TypeScript
        run: pnpm build
